import React, { useEffect, useState } from "react";
import { attemptLogin, CompleteSignIn } from "../../lib/firebase";

/**
 * Checks that the redirect if present actual points to one of our site
 */
const allowedHosts = [
    'localhost',
    'dev-ar.education.ufl.edu',
    'hpvcommunicationtraining.org',
    'hpvcommunicationtraining.com',
    'coe-med-sparc.firebaseapp.com'
]

/**
 * Check if a redirect leads to an approved destination
 * @param redirectUrl 
 * @returns 
 */
function redirectValid(redirectUrl: string) {
    if (redirectUrl == null) { return true; }
    try {
        const { hostname } = new URL(redirectUrl);
        return allowedHosts.includes(hostname);
    } catch {
        return false;
    }
}

/**
 * Creates the feedback used in the feedback message
 * @param status string Status code generated by signin actions
 * @returns string
 */
function generateFeedback(status: string | undefined) {
    switch (status) {
        case 'auth/expired-action-code': 
            return 'Your sign-in link has expired. Please try again.';
        case 'auth/invalid-action-code': 
            return 'Invalid link. Please try again.';
        case 'auth/user-disabled': 
            return 'Your account has been disabled.';
        case 'auth/user-not-found': 
            return 'Please provide an email for a registered user.';
        case 'auth/invalid-email': 
            return 'Please provide an email for a registered user.';
        case 'invalid': 
            return 'Please provide an email for a registered user';
        case 'success': 
            return 'Success! You will be redirected momentarily.';
        case 'sent': 
            return 'A sign-in link has been send to your email. Check your spam folder if you do not see it in your inbox.';
        default: return 'Something went wrong. Please try again.'
    }
}

/**
 * 
 * @param {redirectUrl} 
 * @returns 
 */
export  function EmailLinkForm ({redirectUrl}: {redirectUrl ?: string }) {
    const [feedbackMessage, setFeedbackMessage] = useState('');
    let url: string | URL = location.origin;

    // Check if user is coming from a signin link
    useEffect(() => {
        const tryCompleteSignIn = async () => {
            const result = await CompleteSignIn();
            const feedbackText = typeof(result)==='string' ? generateFeedback(result) : '';
            setFeedbackMessage(feedbackText);
        };
        tryCompleteSignIn();
    }, []);
    
    // Check redirect Url if provided
    if (redirectUrl && redirectValid(redirectUrl)) {
        url = redirectUrl;
    }

    // Options passed to Firebase Auth
    const actionCodeSettings = {
        url: url,
        handleCodeInApp: true, // Required
    }

    const handleSubmit = async (e: React.MouseEvent<HTMLButtonElement>) => {
        e.preventDefault();
        const emailInput = document.querySelector<HTMLInputElement>('#loginEmail');
        const emailValue = emailInput?.value;

        if (!emailValue) {
            setFeedbackMessage('Please enter an email address.');
            return;
        }
        
        // Validate submission and login
        try {
            const status = await attemptLogin(emailValue, actionCodeSettings);
            const feedbackText = typeof(status)==='string' ? generateFeedback(status) : '';
            setFeedbackMessage(feedbackText);
        } catch {
            setFeedbackMessage('Something went wrong. Please refresh the page and try again.');
            return;
        }
    }

    return (
        <div id="login-form-container">
            <form id="sparcLogin" className="">
                <label htmlFor="loginEmail" className="block p-0 mb-2">Email Address</label>
                <input type="email" id="loginEmail" className="border-2 border-black p-2 mb-4 w-full" />
                <div id="loginFeedbackContainer" className=" mb-4">{feedbackMessage}</div>
                <button
                    type="submit"
                    onClick={handleSubmit}
                    className="bg-black w-full p-4 text-white font-800 border-2 border-black hover:bg-white hover:text-black" >
                        Send Sign-in Link
                    </button>
            </form>
        </div>
    );
}